version: "3"

volumes:
  pg-data:
  
networks:
  ovms-bridge:
    driver: bridge
services: 
  ovms-server:
    image: jkalapati/ovms-server
    hostname: ovms-server
    ports: 
      - "9000:9000"
      - "9001:9001"
    expose: 
      - "9000"
    networks: 
      - ovms-bridge
    command: [--port=9000, --model_name=face-detection, --model_path=/models, --shape=auto]
    tty: 
      true
      
  compreface-postgres-db:
    image: exadel/compreface-postgres-db:1.1.0
    restart: always
    container_name: "compreface-postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
      - PGDATA=/pg-data
    volumes:
      - pg-data:/pg-data

  database:
    image: postgres:latest
    restart: always
    container_name: "postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pg-data
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/pg-data

  compreface-admin:
    restart: always
    image: exadel/compreface-admin:1.1.0
    container_name: "compreface-admin"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=-Xmx1g
      - MAX_FILE_SIZE=5MB
      - MAX_REQUEST_SIZE=10MB
    depends_on:
      - compreface-postgres-db
      - compreface-api
      
  compreface-api:
    restart: always
    image: exadel/compreface-api:1.1.0
    container_name: "compreface-api"
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=-Xmx4g
      - SAVE_IMAGES_TO_DB=true
      - MAX_FILE_SIZE=5MB
      - MAX_REQUEST_SIZE=10MB
      - CONNECTION_TIMEOUT=10000:-10000
      - READ_TIMEOUT=60000:-60000
      
  compreface-fe:
    restart: always
    image: exadel/compreface-fe:1.1.0
    container_name: "compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=10M
      - PROXY_READ_TIMEOUT=60000:-60000ms
      - PROXY_CONNECT_TIMEOUT=10000:-10000ms

  compreface-core:
    restart: always
    image: exadel/compreface-core:1.1.0
    container_name: "compreface-core"
    environment:
      - ML_PORT=3000
      - IMG_LENGTH_LIMIT=640
      - UWSGI_PROCESSES=2:-2
      - UWSGI_THREADS=1:-1
