version: "3"

volumes:
  postgres-data:
  
networks: 
  ovms-bridge:
    driver: bridge
services: 
  ovms-server:
    image: jkalapati/ovms-server
    hostname: ovms-server
    ports: 
      - "9000:9000"
      - "9001:9001"
    expose: 
      - "9000"
    networks: 
      - ovms-bridge
    command: [--port=9000, --model_name=face-detection, --model_path=/models, --shape=auto]
    tty: 
      true
      
  ovms-client: 
    image: jkalapati/ovms-client
    environment: 
      SERVER_NAME: ovms-server
      GRPC_PORT: 9000
    ports:
      - "8000:8000"
    networks: 
      - ovms-bridge
    depends_on:
      - ovms-server
    links: 
      - ovms-server
    tty:
      true
      
  compreface-postgres-db:
    image: exadel/compreface-postgres-db:1.1.0
    restart: always
    container_name: "compreface-postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  compreface-admin:
    restart: always
    image: exadel/compreface-admin:1.1.0
    container_name: "compreface-admin"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=true
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=-Xmx4g
      - MAX_FILE_SIZE=5MB
      - MAX_REQUEST_SIZE=10MB
    depends_on:
      - compreface-postgres-db
      - compreface-api
