volumes:
  postgres-data:

services:
  compreface-postgres-db:
    image: exadel/compreface-postgres-db:1.1.0
    restart: always
    container_name: "compreface-postgres-db"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    restart: always
    image: exadel/compreface-admin:1.1.0
    container_name: "compreface-admin"
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:
    restart: always
    image: exadel/compreface-api:1.1.0
    container_name: "compreface-api"
    depends_on:
      - compreface-postgres-db

  compreface-fe:
    restart: always
    image: exadel/compreface-fe:1.1.0
    container_name: "compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
      
  compreface-core:
    restart: always
    image: exadel/compreface-core:1.1.0
    container_name: "compreface-core"
